language: cpp
dist: trusty
sudo: false
script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. && make && ./runtests
compiler:
  - clang
  - gcc
