language: cpp
dist: trusty
sudo: true
script: ./run-build.sh
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - lcov

after_success:
  - ./create-lcov-report.sh
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

env:
  global:
    - LANG="en_US.UTF-8"
