name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+

jobs:
  build:
    if: ${{ github.repository == 'Netflix-Skunkworks/atlas-native-client' }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - {compiler: gcc}
          - {compiler: clang}
    env:
      LANG: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies (clang)
        if: startsWith(matrix.compiler, 'clang')
        run: |
          sudo apt-get update
          sudo apt-get install -y curl software-properties-common
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository -y "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-5.0 main"
          sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y clang-5.0

      - name: Build and Test (clang)
        if: startsWith(matrix.compiler, 'clang')
        env:
          CC: "clang-5.0"
          CXX: "clang++-5.0"
        run: ./run-build.sh

      - name: Install Dependencies (gcc)
        if: startsWith(matrix.compiler, 'gcc')
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y g++-5 lcov

      - name: Build and Test (gcc)
        if: startsWith(matrix.compiler, 'gcc')
        env:
          CC: "gcc-5"
          CXX: "g++-5"
        run: ./run-build.sh
